







	



.build/uno/LiquidCrystal/LiquidCrystal.d : /usr/share/arduino/libraries/LiquidCrystal/LiquidCrystal.cpp
	@mkdir -p .build/uno/LiquidCrystal
	@/usr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/libraries/Stepper -I/usr/share/arduino/libraries/SPI -I/usr/share/arduino/libraries/DHT -I/usr/share/arduino/libraries/SoftwareSerial -I/usr/share/arduino/libraries/Servo -I/usr/share/arduino/libraries/LiquidCrystal -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/libraries/SD -I/usr/share/arduino/libraries/SD/utility -I/usr/share/arduino/libraries/Ethernet -I/usr/share/arduino/libraries/Ethernet/utility -I/usr/share/arduino/libraries/EEPROM -I/usr/share/arduino/libraries/Firmata  -MM $^ > $@
	
	@printf ".build/uno/LiquidCrystal/LiquidCrystal.d .build/uno/LiquidCrystal/" | cat - $@ > $@~ && mv $@~ $@



.build/uno/LiquidCrystal/dependencies.d : .build/uno/LiquidCrystal/LiquidCrystal.d
	@echo [96mScanning dependencies of LiquidCrystal[0m
	@mkdir -p .build/uno/LiquidCrystal
	@cat $^ > $@;

all : .build/uno/LiquidCrystal/dependencies.d
	@true

